# Generated by Django 6.0.2 on 2026-03-04 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
