# Generated by Django 6.0.2 on 2026-03-11 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_forum_slug_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='forums.reply'),
        ),
    ]
