# Generated by Django 6.0.2 on 2026-03-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_reply_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='parent',
        ),
    ]
