# Generated by Django 6.0.2 on 2026-03-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_alter_reply_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='faculty',
        ),
        migrations.AddField(
            model_name='forum',
            name='faculty',
            field=models.ManyToManyField(related_name='forums', to='forums.faculty'),
        ),
    ]
