# Generated by Django 6.0.2 on 2026-03-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_remove_forum_faculty_forum_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
