# Generated by Django 6.0.2 on 2026-03-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
    ]
